parameters:
    mistral.api_key: '%env(MISTRAL_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\MistralClient:
        arguments:
            $mistralApiKey: '%mistral.api_key%'

    # (optionnel si tu l'utilises encore)
    App\Service\MistralQcmGenerator:
        arguments:
            $mistralApiKey: '%mistral.api_key%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
